version: '3'
services:
  redis:
    image: redis:latest
    container_name: "redis"
    ports:
      - 6379:6379
    restart: always
    volumes:
      - "/etc/localtime:/etc/localtime:ro"

  mysql:
    image: mysql:latest
    container_name: "mysql"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
    ports:
      - 3306:3306
    restart: always
    volumes:
      - "/etc/localtime:/etc/localtime:ro"

  etcd:
    image: gcr.io/etcd-development/etcd:latest
    container_name: "etcd"
    ports: 
      - 2379:2379
      - 2380:2380
    environment:
      - "ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379"
      - "ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379"
      - "ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380"
      - "ETCD_INITIAL_ADVERTISE_PEER_URLS=http://0.0.0.0:2380"
      - "ALLOW_NONE_AUTHENTICATION=yes"
      - "ETCD_INITIAL_CLUSTER=node1=http://0.0.0.0:2380"
      - "ETCD_NAME=node1"

    restart: always
    volumes:
      - "/etc/localtime:/etc/localtime:ro"


#   alpine:
#     build:
#         context: .
#         dockerfile: scratch.Dockerfile
#     container_name: "alpine"
#     ports:
#       - 28893:8888
#     volumes:
#       - .:/code


# docker-compose up -d
# docker-compose stop
# docker-compose start
# docker-compose down
